version: '3.9'

services:
  db: 
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    #shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - ./.env.local
    volumes:
      - ./db-data:/var/lib/postgresql/data
      # init db schema
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - default
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - adminer-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.local
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - default

networks:
  adminer-net:
    external: false

  